version: '3'
networks:
  phpngaos_network:
    driver: bridge

services:
  app:
    build:
      context: ./
      dockerfile: docker/app.dockerfile
    image: phpngaos_app
    networks:
      - phpngaos_network
    container_name: phpngaos_app
    volumes:
      - ./:/var/www
    restart: always

  web:
    build:
      context: ./
      dockerfile: docker/web.dockerfile
    image: phpngaos_web
    networks:
      - phpngaos_network
    container_name: phpngaos_web
    volumes:
      - ./:/var/www
    ports:
      - "8000:80"
    depends_on:
      - app
    restart: always
